### ISSUE TITLE
ANN: Please test against astropy v5.1rc1

### ISSUE THREAD

**Issue by pllim** [astropy/specreduce#106]
Hello. You appear to be on track to be a Astropy Coordinated Package. Please report back at https://github.com/astropy/astropy/wiki/v5.1-RC-testing . Thank you!

**Comment by tepickering** [comment]
looks good: https://github.com/astropy/specreduce/runs/6462166166?check_suite_focus=true

**Comment by pllim** [comment]
Thanks!
