### ISSUE TITLE
DOC: Add CITATION file

### ISSUE THREAD

**Issue by dhomeier** [astropy/specreduce#108]
As this package is now under review for becoming an Astropy coordinated package, could you add instructions on how to preferably cite this package and any relevant publications related to it; most conveniently by putting the info (possibly with BibTeX etc.) into a `CITATION` file?
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
for further recommendations.

**Comment by pllim** [comment]
@tepickering , are you able to address this or know someone who can, so we can move forward with https://github.com/astropy/astropy.github.com/pull/489 ? Thanks!

**Comment by tepickering** [comment]
https://github.com/astropy/specreduce/pull/110
