### ISSUE TITLE
Subpixel aperture widths produce incorrect weights

### ISSUE THREAD

**Issue by ojustino** [astropy/specreduce#131]
We realized this while updating `_get_boxcar_weights()` in #125. @kecnry has worked out a solution that looks promising, but the need to test it more extensively means it will probably end up in a different pull request. In the meantime, #125 should produce correct weights in all scenarios where `width >= 1`.

**Comment by kecnry** [comment]
Just so that it isn't lost, this is what I came up with to swap `_get_boxcar_weights` (but haven't tested it or cleaned it up enough to open a PR yet):

```
def _get_boxcar_weights(center, hwidth, npix):
    weights = np.zeros(npix)

    lower_edge = max(-0.5, center-hwidth)
    upper_edge = min(center+hwidth, npix-0.5)

    weights[int(round(lower_edge))+1:int(round(upper_edge))] = 1

    weights[int(round(lower_edge))] = round(lower_edge) + 0.5 - lower_edge
    weights[int(round(upper_edge))] = upper_edge - (round(upper_edge) - 0.5)
    return weights
```

**Comment by kecnry** [comment]
Note that the solution proposed above does not account for the case in #139 - we'll probably want to modify the above solution to also account for the lower and/or upper edge extending above the image.
