### ISSUE TITLE
Add vacuum to air transformations 

### ISSUE THREAD

**Issue by crawfordsm** [astropy/specreduce#17]
This functionality should be available in astropy

**Comment by ivastar** [comment]
Transformation function currently exists here: 
https://github.com/weaverba137/pydl/blob/master/pydl/goddard/astro.py

Probably should be in specutils: @nmearl

**Comment by Knusper** [comment]
Note that different methods have been adopted by different communities.  I think the most "accurate" transformation is the one that is used by high-resolution spectroscopists:
https://www.astro.uu.se/valdwiki/Air-to-vacuum%20conversion

**Comment by saimn** [comment]
There is already some code in specutils:
https://github.com/astropy/specutils/blob/4afeee015eb6304bc1844e423f82c16b22c532d7/specutils/utils/wcs_utils.py#L457-L458
But I guess it should be more visible, and I cannot find in the documentation.

**Comment by tepickering** [comment]
this functionality has been implemented in `specutils.utils.wcs_utils.air_to_vac` and `specutils.utils.wcs_utils.vac_to_air` and is now released. `specreduce` will import and use those routines.
