### ISSUE TITLE
Add specreduce to conda-forge

### ISSUE THREAD

**Issue by astrofrog** [astropy/specreduce#184]
We should add a specreduce recipe to conda-forge

**Comment by hpparvi** [comment]
I can look into this if nobody else has the time. Who can I list as the recipe maintainers?

**Comment by pllim** [comment]
> Who can I list as the recipe maintainers?

At the very least, yourself and @mwcraig . Others on Team page (Tim Pickering, Erik Tollerud, Kyle Conroy, Clare Shanahan) can be added if they can commit to the task and comfortable with conda-forge recipe maintenance.

**Comment by hpparvi** [comment]
Thanks, @mwcraig! The PR is merged, and specreduce should be available from conda-forge later today. If anyone shows interest, we can add more maintainers later.
