### ISSUE TITLE
Specreduce layout inconsistent with Photutils and Specutils

### ISSUE THREAD

**Issue by orifox** [astropy/specreduce#189]
I recommend having a similar formatting, along with a specific logo, consistent with Photutils and Specutils.

**Comment by rosteen** [comment]
Are you talking about the readthedocs page? The Github Readme? Or something else?

**Comment by pllim** [comment]
I am guessing it is ReadTheDocs.

**Comment by pllim** [comment]
Basically you need to create assets like those in https://github.com/astropy/specutils/tree/main/docs/_static and then use them in the docs.
