### ISSUE TITLE
Background returns incorrect units

### ISSUE THREAD

**Issue by cshanahan1** [astropy/specreduce#213]
The following should return flux in DN, not DN**2:

`img = np.tile((np.arange(1., 13)), (13, 1)) * u.DN`
`trace = FlatTrace(img, 2)`
`background = Background(img, trace)`
`background.bkg_image()`

**Comment by hpparvi** [comment]
I think you fixed this in #221. Trying to reproduce the issue with the latest commit in main (2cc466d) returns the flux correctly in DN.

**Comment by hpparvi** [comment]
This issue was fixed by @cshanahan1 in #221.
