### ISSUE TITLE
github actions vs travis for CI

### ISSUE THREAD

**Issue by tepickering** [astropy/specreduce#48]
in #47 i added the configuration file to enable the use of github actions for testing and CI. currently, this repo is using both that and travis. is there a desire to keep using travis or should we just switch to and stick with github actions going forward? actions has the advantage of offering better github integration (obviously) and has more flexibility to more easily do things other than CI (e.g. container builds). travis, however, offers some CI features that actions still hasn't implemented (e.g. `[ci skip]`), though it's possible to implement those features in one's own config as needed.

**Comment by crawfordsm** [comment]
My feeling would be just to go with actions and minimize the amount of overhead or things to pay attention to at the moment.    We can always revisit it if we find that we are missing the travis builds.

**Comment by tepickering** [comment]
yeah, i concur. i find having the 'actions' tab right in the repo to be extremely handy.
