### ISSUE TITLE
apextract_demo is not a valid notebook

### ISSUE THREAD

**Issue by saimn** [astropy/specreduce#76]
https://github.com/astropy/specreduce/blob/main/notebook_sandbox/apextract_demo.ipynb seems to be a tar archive containing the notebooks:
```
❯ file notebook_sandbox/apextract_demo.ipynb
notebook_sandbox/apextract_demo.ipynb: POSIX tar archive (GNU)

❯ tar --list -f notebook_sandbox/apextract_demo.ipynb
apo05.ipynb
flatfield_demo.ipynb
fluxcal_demo.ipynb
identify_demo.ipynb
```

**Comment by tepickering** [comment]
that's awkward. the notebooks contained in there are in the repo themselves, though, so this file can just be deleted. a real apextract demo notebook is on my todo list to reflect the recent and ongoing work done on tracing and extraction.
