### ISSUE TITLE
TST: Replace doc_test job with RTD PR builder

### ISSUE THREAD

**Issue by pllim** [astropy/specreduce#94]
https://github.com/astropy/specreduce/blob/85af34074dcbf034220d044b7691f427404563d4/.github/workflows/tox-tests.yml#L52-L53

The comment about checking link is inaccurate because it does not run linkcheck defined in `tox.ini`. I see you already have RTD set up, so you should just do this: https://docs.readthedocs.io/en/stable/pull-requests.html

As for linkcheck, it is best run as a cron job. Links can be flaky, there is no need to check it every commit.

**Comment by tepickering** [comment]
the RTD config itself was out of date and broken. addressed in #107 and the suggested configuration change has been made. looks like it's building fine now: https://specreduce--107.org.readthedocs.build/en/107/
