### ISSUE TITLE
add more PyPI maintainers

### ISSUE THREAD

**Issue by tepickering** [astropy/specreduce#98]
currently, the PyPI releases are only maintained via @tepickering's account. need to add some more for redundancy.

**Comment by ojustino** [comment]
Hi @tepickering, @kecnry and I are both fine with becoming maintainers on PyPI if you'd like to add us. Are you still on the `specreduce` Slack channel? We can coordinate there if needed.

**Comment by tepickering** [comment]
i responded via slack. send me your `pypi` usernames so i can add you as maintainers on `pypi.org`. once that's done, i'll close this.

**Comment by tepickering** [comment]
new maintainers added as of 2022-08-16.
